artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: ''
  unzip_dir: data



prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_UNet.pth
  updated_base_model_path: artifacts/prepare_base_model/updated_base_UNet.pth


training:
  root_dir: artifacts/training
  stage_dir: model
  trained_model_path: artifacts/training/trained_Unet.pth
